# Generated by Django 3.1.1 on 2020-09-26 10:20

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepagecarouselimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='label',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='sublabel',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
