# Generated by Django 3.1.1 on 2020-09-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200926_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecarouselimages',
            name='label',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselimages',
            name='sublabel',
        ),
    ]
