# Generated by Django 3.1.1 on 2020-09-22 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlecPage',
            new_name='FlexPage',
        ),
    ]
