# Generated by Django 3.1.1 on 2020-09-22 18:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_auto_20200922_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', requred=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Additional text', required=True))]))], blank=True, null=True),
        ),
    ]
